version: "2.4"
services:
  web:
    container_name: web
    build: .
    links:
      - redis
    environment:
      - FLASK_UPLOAD_FOLDER=/tmp/upload/
      - GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
      - REDIS_HOST=redis
  redis:
    image: redis
    container_name: redis
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
    links:
      - web
